### ISSUE TITLE
Question about ys_ data

### ISSUE THREAD

**Issue by Shi-Qi-Li** [gktejus/DMF-Synch#3]
Hi @gktejus,
Thanks for sharing the code! I have a question about the `ys_` data. I downloaded the provided 1DSfM dataset, however, I found the `ys_` in `XXX_obs.pt` is strange. I thought the `ys_` contain the observable parts in `Z` matrix, but the `ys_` loaded from `obs.pt` contain ones and zeros.
 
![2023-09-03 23-01-36屏幕截图](https://github.com/gktejus/DMF-synch/assets/29630040/8cd6502a-d68a-4312-9c29-9cef2a02aea9)

**Comment by gktejus** [comment]
@Shi-Qi-Li You scared me for a second there, I was thinking I trained on the wrong data lol. If you look closely into `ys_`, you'll see it's not just ones and zeroes :)

```
>print(ys_[:30])

>tensor([ 1.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,  0.0000,
         1.0000,  0.9615,  0.0025,  0.2749,  0.0024,  0.9998, -0.0176, -0.2749,
         0.0176,  0.9613,  0.8945, -0.2331, -0.3816,  0.0854,  0.9267, -0.3659,
         0.4389,  0.2947,  0.8488,  0.7976, -0.2632, -0.5426],
       dtype=torch.float64)
```

The indices corresponding to the relative rotation of camera i relative to camera i again, would always be identity, hence it's rotation matrix would always be an Identity matrix ( and will be always counted as observed ). Hence, when you do a `print(ys_)`, it shows you the first 3 and last 3 elements of the array, and those will always be 0/1 given that they are part of an identity rotation matrix. 

Let me know if my explanation didn't make sense. I'd be happy to clarify :)

**Comment by Shi-Qi-Li** [comment]
> @Shi-Qi-Li You scared me for a second there, I was thinking I trained on the wrong data lol. If you look closely into `ys_`, you'll see it's not just ones and zeroes :)
> 
> ```
> >print(ys_[:30])
> 
> >tensor([ 1.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,  0.0000,
>          1.0000,  0.9615,  0.0025,  0.2749,  0.0024,  0.9998, -0.0176, -0.2749,
>          0.0176,  0.9613,  0.8945, -0.2331, -0.3816,  0.0854,  0.9267, -0.3659,
>          0.4389,  0.2947,  0.8488,  0.7976, -0.2632, -0.5426],
>        dtype=torch.float64)
> ```
> 
> The indices corresponding to the relative rotation of camera i relative to camera i again, would always be identity, hence it's rotation matrix would always be an Identity matrix ( and will be always counted as observed ). Hence, when you do a `print(ys_)`, it shows you the first 3 and last 3 elements of the array, and those will always be 0/1 given that they are part of an identity rotation matrix.
> 
> Let me know if my explanation didn't make sense. I'd be happy to clarify :)

Thanks for your reply! I was trapped by the identity matrix at beginning and end.
